const plans = [
    {
      id: 1,
      name: "Principiante",
      duration: "4 semanas",
      features: [
        { id: 1, description: "Plan de entrenamiento", included: true },
        { id: 2, description: "Plan de 4 semanas", included: true },
        { id: 3, description: "Acceso a videos de ejercicios", included: true },
        { id: 4, description: "Asesoramiento por expertos", included: true },
        { id: 5, description: "Seguimiento de progreso", included: false },
        { id: 6, description: "Acceso a comunidad en línea", included: true },
        { id: 7, description: "Sesiones en vivo", included: false },
        { id: 8, description: "Evaluación de la forma física", included: false },
        { id: 9, description: "Rutinas de calentamiento", included: false },
        { id: 10, description: "Guía de nutrición", included: false },
      ],
      price: "$29",
    },
    {
      id: 2,
      name: "Intermedio",
      duration: "6 semanas",
      features: [
        { id: 11, description: "Plan de entrenamiento", included: true },
        { id: 12, description: "Plan de 6 semanas", included: true },
        { id: 13, description: "Acceso a videos de ejercicios", included: true },
        { id: 14, description: "Asesoramiento por expertos", included: true },
        { id: 15, description: "Seguimiento de progreso", included: true },
        { id: 16, description: "Acceso a comunidad en línea", included: true },
        { id: 17, description: "Sesiones en vivo", included: false },
        { id: 18, description: "Evaluación de la forma física", included: false },
        { id: 19, description: "Rutinas de calentamiento", included: true },
        { id: 20, description: "Guía de nutrición", included: false },
      ],
      price: "$49",
    },
    {
      id: 3,
      name: "Avanzado",
      duration: "8 semanas",
      features: [
        { id: 21, description: "Plan de entrenamiento", included: true },
        { id: 22, description: "Plan de 8 semanas", included: true },
        { id: 23, description: "Acceso a videos de ejercicios", included: true },
        { id: 24, description: "Asesoramiento por expertos", included: true },
        { id: 25, description: "Seguimiento de progreso", included: true },
        { id: 26, description: "Acceso a comunidad en línea", included: true },
        { id: 27, description: "Sesiones en vivo", included: true },
        { id: 28, description: "Evaluación de la forma física", included: true },
        { id: 29, description: "Rutinas de calentamiento", included: true },
        { id: 30, description: "Guía de nutrición", included: true },
      ],
      price: "$69",
    },
    {
      id: 4,
      name: "Pérdida de Grasa",
      duration: "12 semanas",
      features: [
        { id: 31, description: "Plan para pérdida de grasa", included: true },
        { id: 32, description: "Plan de 12 semanas", included: true },
        { id: 33, description: "Recetas de comidas saludables", included: true },
        { id: 34, description: "Asesoramiento por correo", included: true },
        { id: 35, description: "Entrenamiento en video", included: true },
        { id: 36, description: "Rutinas de cardio", included: true },
      ],
      price: "$79",
    },
    {
      id: 5,
      name: "Masa Muscular",
      duration: "10 semanas",
      features: [
        { id: 37, description: "Plan de aumento de masa muscular", included: true },
        { id: 38, description: "Plan de 10 semanas", included: true },
        { id: 39, description: "Videos de ejercicios demostrativos", included: true },
        { id: 40, description: "Asesoramiento personalizado", included: true },
        { id: 41, description: "Entrenamiento en video", included: true },
        { id: 42, description: "Guía de nutrición", included: true },
      ],
      price: "$89",
    },
    {
      id: 6,
      name: "Yoga",
      duration: "6 semanas",
      features: [
        { id: 43, description: "Entrenamiento de yoga", included: true },
        { id: 44, description: "Plan de 6 semanas", included: true },
        { id: 45, description: "Sesiones de relajación guiada", included: true },
        { id: 46, description: "Acceso a comunidad en línea", included: true },
        { id: 47, description: "Ejercicios de respiración", included: true },
        { id: 48, description: "Videos de práctica de yoga", included: true },
      ],
      price: "$39",
    },
  ];
  

  
// const plans = [
//     {
//         name: "Guía para principiantes",
//         description: "Un plan de entrenamiento diseñado para principiantes.",
//         duration: "4 semanas",
//         image: "plan_principiantes.jpg",
//         price: "$29",
//     },
//     {
//         name: "Intensidad Intermedia",
//         description: "Lleva tus entrenamientos al siguiente nivel con este plan intermedio.",
//         duration: "6 semanas",
//         image: "plan_intermedio.jpg",
//         price: "$49",
//     },
//     {
//         name: "Atleta Avanzado",
//         description: "Supérate con este programa de entrenamiento avanzado.",
//         duration: "8 semanas",
//         image: "plan_avanzado.jpg",
//         price: "$69",
//     },
//     {
//         name: "Fusión para la Pérdida de Grasa",
//         description: "Un plan especializado para la pérdida efectiva de grasa.",
//         duration: "12 semanas",
//         image: "plan_perdida_grasa.jpg",
//         price: "$79",
//     },
//     {
//         name: "Locura para el Aumento de Masa Muscular",
//         description: "Aumenta tu masa muscular con este plan intensivo.",
//         duration: "10 semanas",
//         image: "plan_masa_muscular.jpg",
//         price: "$89",
//     },
//     {
//         name: "Yoga y Mindfulness",
//         description: "Un enfoque holístico para la salud y el bienestar.",
//         duration: "6 semanas",
//         image: "plan_yoga.jpg",
//         price: "$39",
//     },
//   ];
  
export default plans;